#Video Games Sales Analytics.

import numpy as np
import pandas as pd
import matplotlib.pyplot as mp

class GameSales:
    def __init__(self,copiesbypublisher,boughtbyregion,revenuegeneratedbygenre
                 ,scoreaffectsales,topgamesbyrevenue):
        self.copiesbypublisher = copiesbypublisher
        self.boughtbyregion = boughtbyregion
        self.revenuegeneratedbygenre = revenuegeneratedbygenre
        self.scoreaffectsales = scoreaffectsales
        self.topgamesbyrevenue = topgamesbyrevenue

        self.CP = None
        self.BR = None
        self.RG = None
        self.SS = None
        self.TGR = None

    def AnalyzeData(self):
        self.CP = pd.read_csv(self.copiesbypublisher)
        self.BR = pd.read_csv(self.boughtbyregion)
        self.RG = pd.read_csv(self.revenuegeneratedbygenre)
        self.SS = pd.read_csv(self.scoreaffectsales)
        self.TGR = pd.read_csv(self.topgamesbyrevenue)
        print("-----Data Analyzed Successfully-------")
        with open("../OtherFiles/GameSales.txt","w") as file:
            file.write("")

    def VisualizeData(self):
        with open("../OtherFiles/GameSales.txt", "a") as file:
            file.write("\nVideo Games Sales Analytics\n")
            
            # --- 1. Most Copies Sold By Publisher ---
            # Cast X to string and drop missing rows to prevent TypeErrors
            cp_clean = self.CP.dropna(subset=["publisher", "copies_sold"])
            mostcopies = cp_clean.groupby("publisher")["copies_sold"].sum()
            file.write(f"Most Copies By Publisher : {mostcopies.idxmax()}\n")
            
            mp.bar(x=cp_clean["publisher"].astype(str), height=cp_clean["copies_sold"])
            mp.title("Most Copies Sold by Publisher")
            mp.xticks(rotation=45)
            mp.show()
            
            # --- 2. Most Games Bought By Region (Where your error happened) ---
            # Fix: Ensure region names are strictly strings and handle any NaN values
            br_clean = self.BR.dropna(subset=["region", "gamesbought"])
            top_region = br_clean.groupby("region")["gamesbought"].sum()
            file.write(f"Top Region by Games Bought : {top_region.idxmax()}\n")
            
            # Force .astype(str) so Matplotlib gets 'str' instead of 'float'
            mp.bar(x=br_clean["region"].astype(str), height=br_clean["gamesbought"])
            mp.title("Most Games Bought By Region")
            mp.show()
            
            # --- 3. Most Revenue Generated By Genre ---
            rg_clean = self.RG.dropna(subset=["genre", "revenue"])
            top_genre = rg_clean.groupby("genre")["revenue"].sum()
            file.write(f"Top Genre by Revenue : {top_genre.idxmax()}\n")
            
            mp.bar(x=rg_clean["genre"].astype(str), height=rg_clean["revenue"])
            mp.title("Most Revenue Generated By Genre")
            mp.show()
            
            # --- 4. Score Affect Sales ---
            ss_clean = self.SS.dropna(subset=["copies_sold", "reviewscore"])
            file.write("Generated Correlation: Review Score vs Copies Sold\n")
            
            # Note: Changed height= to y= because mp.scatter uses 'y'
            mp.scatter(x=ss_clean["copies_sold"], y=ss_clean["reviewscore"])
            mp.title("Score Affect Sales")
            mp.xlabel("Copies Sold")
            mp.ylabel("Review Score")
            mp.show()
            
            # --- 5. Top Games By Revenue ---
            tgr_clean = self.TGR.dropna(subset=["games", "revenue"])
            top_game = tgr_clean.groupby("games")["revenue"].sum()
            file.write(f"Top Game By Revenue : {top_game.idxmax()}\n")
            
            mp.bar(x=tgr_clean["games"].astype(str), height=tgr_clean["revenue"])
            mp.title("Top Games By Revenue")
            mp.xticks(rotation=45)
            mp.show()


GS = GameSales("../StoreData/VideoGamesSalesAnalytics/MostCopiesSoldByPublisher",
               "../StoreData/VideoGamesSalesAnalytics/MostGamesBoughtByRegion",
               "../StoreData/VideoGamesSalesAnalytics/MostRevenueGeneratedByGenre",
               "../StoreData/VideoGamesSalesAnalytics/ScoreAffectSales",
               "../StoreData/VideoGamesSalesAnalytics/TopGamesByRevenue")

GS.AnalyzeData()
GS.VisualizeData()