#Online Store Analytics.
import numpy as np
import pandas as pd
import matplotlib.pyplot as mp

class OnlineStore:
    def __init__(self):

        self.CG = None
        self.CS = None
        self.CSM = None
        self.CuS = None
        self.T = None

    def AnalyzeData(self):
        self.CG = pd.read_csv("../StoreData/OnlineStoreAnalytics/CategoryGeneratingMostMoney")
        self.CS = pd.read_csv("../StoreData/OnlineStoreAnalytics/CategorySpendingAboveAverage")
        self.CSM = pd.read_csv("../StoreData/OnlineStoreAnalytics/CitySpendingMostMoney")
        self.CuS = pd.read_csv("../StoreData/OnlineStoreAnalytics/CustomerSpendingAboveAverage")
        self.T = pd.read_csv("../StoreData/OnlineStoreAnalytics/Top10Customers")
        print("------Data Analyzed Successfully-------")

    def VisualizeData(self):
        print("Visualizing The Data + Making The Report")

        # 1. Category Generating Most Money
        mp.figure(figsize=(8, 5))
        mp.bar(self.CG["category"], self.CG["totalcategoryrevenue"])
        mp.title("Revenue Generated By Category")
        mp.xlabel("Category")
        mp.ylabel("Revenue")
        mp.xticks(rotation=45)
        mp.tight_layout()
        mp.show()

        # 2. Categories Spending Above Average
        mp.figure(figsize=(8, 5))
        mp.bar(self.CS["category"], self.CS["total_spent"])
        mp.title("Categories Spending Above Average")
        mp.xlabel("Category")
        mp.ylabel("Total Spent")
        mp.xticks(rotation=45)
        mp.tight_layout()
        mp.show()

        # 3. City Spending Most Money
        mp.figure(figsize=(8, 5))
        mp.bar(self.CSM["city"], self.CSM["money"])
        mp.title("Money Spent By City")
        mp.xlabel("City")
        mp.ylabel("Money")
        mp.xticks(rotation=45)
        mp.tight_layout()
        mp.show()

        # 4. Customers Spending Above Average
        mp.figure(figsize=(8,5))
        mp.hist(self.CuS["total_spent"], bins=10)
        mp.title("Distribution of Customer Spending Above Average")
        mp.xlabel("Total Spent")
        mp.ylabel("Number of Customers")
        mp.tight_layout()
        mp.show()

        # 5. Top 10 Customers
        customer_col = self.T.columns[0]
        spent_col = self.T.columns[1]

        mp.figure(figsize=(10, 5))
        mp.bar(self.T[customer_col], self.T[spent_col])
        mp.title("Top 10 Customers")
        mp.xlabel("Customer")
        mp.ylabel("Total Spent")
        mp.xticks(rotation=45)
        mp.tight_layout()
        mp.show()

        # Generate Report
        top_category = self.CG.loc[self.CG["totalcategoryrevenue"].idxmax(), "category"]
        top_city = self.CSM.loc[self.CSM["money"].idxmax(), "city"]
        top_customer = self.T.loc[self.T[spent_col].idxmax(), customer_col]

        with open("OnlineStoreReport.txt", "w") as file:
            file.write("Online Store Analytics Report\n")
            file.write("============================\n")
            file.write(f"Highest Revenue Category : {top_category}\n")
            file.write(f"Top Spending City : {top_city}\n")
            file.write(f"Top Customer : {top_customer}\n")
            file.write(f"Customers Spending Above Average : {len(self.CuS)}\n")
            file.write(f"Categories Spending Above Average : {len(self.CS)}\n")

        print("Report Generated Successfully")

OS = OnlineStore()
OS.AnalyzeData()
OS.VisualizeData()
        